In [1]:
import numpy as np


In [4]:

with open("corpus.txt","r") as file:
    corpus = file.read().splitlines()

print("Corpus:")
print(corpus)


Corpus:
['I love AI', 'AI is powerful', 'Python is easy']


In [5]:
corpus = [sentence.lower().strip() for sentence in corpus]

print("Preprocessed Corpus:")
print(corpus)

Preprocessed Corpus:
['i love ai', 'ai is powerful', 'python is easy']


In [6]:
tokenized = []

for sentence in corpus:
    words = sentence.split()
    tokenized.append(words)

print("Tokenized Corpus:")
print(tokenized)

Tokenized Corpus:
[['i', 'love', 'ai'], ['ai', 'is', 'powerful'], ['python', 'is', 'easy']]


In [7]:
vocab = {}
index = 0

for sentence in tokenized:

    for word in sentence:

        if word not in vocab:

            vocab[word] = index
            index += 1

print("Vocabulary:")
print(vocab)

Vocabulary:
{'i': 0, 'love': 1, 'ai': 2, 'is': 3, 'powerful': 4, 'python': 5, 'easy': 6}


In [8]:
token_ids = []

for sentence in tokenized:

    ids = [vocab[word] for word in sentence]

    token_ids.append(ids)

print("Token IDs:")
print(token_ids)

Token IDs:
[[0, 1, 2], [2, 3, 4], [5, 3, 6]]


In [9]:
input_sequences = []
target_sequences = []

for ids in token_ids:
    input_sequences.append(ids[:-1])
    target_sequences.append(ids[1:])

print("Input Sequences:")
print(input_sequences)

print("\nTarget Sequences:")
print(target_sequences)

Input Sequences:
[[0, 1], [2, 3], [5, 3]]

Target Sequences:
[[1, 2], [3, 4], [3, 6]]


In [10]:
embedding_dim = 4

embedding_matrix = np.random.rand(len(vocab), embedding_dim)

print("Embedding Matrix:\n")
print(embedding_matrix)

Embedding Matrix:

[[0.56493697 0.18952208 0.68050672 0.42042527]
 [0.62970416 0.64157953 0.92052077 0.50784389]
 [0.22362323 0.29122247 0.07946578 0.91761154]
 [0.4517345  0.00580026 0.3346265  0.63921114]
 [0.76263295 0.10096357 0.87337091 0.42329635]
 [0.61834701 0.09622506 0.22459017 0.9241025 ]
 [0.39366717 0.42464017 0.10203201 0.69232009]]


In [11]:
embedded_sequences = []

for sequence in input_sequences:
    embedded = embedding_matrix[sequence]
    embedded_sequences.append(embedded)

print("Embedded Input:\n")
print(embedded_sequences[0])

Embedded Input:

[[0.56493697 0.18952208 0.68050672 0.42042527]
 [0.62970416 0.64157953 0.92052077 0.50784389]]


In [12]:
position = np.arange(len(input_sequences[0])).reshape(-1,1)

embedded_sequences[0] = embedded_sequences[0] + position

print("After Positional Encoding:\n")
print(embedded_sequences[0])

After Positional Encoding:

[[0.56493697 0.18952208 0.68050672 0.42042527]
 [1.62970416 1.64157953 1.92052077 1.50784389]]


In [13]:
sequence_length = len(input_sequences[0])

causal_mask = np.tril(np.ones((sequence_length, sequence_length)))

print("Causal Mask:\n")
print(causal_mask)

Causal Mask:

[[1. 0.]
 [1. 1.]]


In [14]:
Q = embedded_sequences[0]
K = embedded_sequences[0]
V = embedded_sequences[0]

attention_scores = np.dot(Q, K.T)

print("Attention Scores:\n")
print(attention_scores)

Attention Scores:

[[ 0.9949192   3.17265866]
 [ 3.17265866 11.31271223]]


In [15]:
masked_scores = attention_scores * causal_mask

print("Masked Attention Scores:\n")
print(masked_scores)

Masked Attention Scores:

[[ 0.9949192   0.        ]
 [ 3.17265866 11.31271223]]


In [16]:
exp_scores = np.exp(masked_scores)

softmax = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

print("Softmax Output:\n")
print(softmax)

Softmax Output:

[[7.30058461e-01 2.69941539e-01]
 [2.91536558e-04 9.99708463e-01]]


In [17]:
attention_output = np.dot(softmax, V)

print("Attention Output:\n")
print(attention_output)

Attention Output:

[[0.85236187 0.5814927  1.01523802 0.71396473]
 [1.62939374 1.6411562  1.92015926 1.50752687]]


In [20]:
output_weights = np.random.rand(embedding_dim, len(vocab))

logits = np.dot(attention_output, output_weights)

print("Logits:")
print(logits)

Logits:
[[2.07193867 1.91310543 0.92704472 2.021641   1.18471352 1.43354327
  1.0470031 ]
 [4.47245287 4.21616234 2.12494606 4.15533279 2.63286198 3.1956301
  2.02444503]]


In [21]:
predicted_token = np.argmax(logits, axis=1)

print("Predicted Token IDs:")
print(predicted_token)

Predicted Token IDs:
[0 0]


In [22]:
probabilities = np.exp(logits)
probabilities = probabilities / np.sum(probabilities, axis=1, keepdims=True)

loss = 0

for i in range(len(target_sequences[0])):
    loss -= np.log(probabilities[i][target_sequences[0][i]])

loss = loss / len(target_sequences[0])

print("Cross Entropy Loss:", loss)

Cross Entropy Loss: 2.565607051591064


In [23]:
id_to_token = {value: key for key, value in vocab.items()}

print("Generated Tokens:\n")

for token in predicted_token:
    print(id_to_token[token])

Generated Tokens:

i
i


In [24]:
print("=" * 50)
print("Autoregressive Causal Language Model")
print("=" * 50)

print("\nCorpus:")
print(corpus)

print("\nVocabulary Size:", len(vocab))

print("\nToken IDs:")
print(token_ids)

print("\nMerge Rules: Already learned using BPE")

print("\nNext Token Prediction Completed Successfully!")

print("\nProject Completed Successfully!")

Autoregressive Causal Language Model

Corpus:
['i love ai', 'ai is powerful', 'python is easy']

Vocabulary Size: 7

Token IDs:
[[0, 1, 2], [2, 3, 4], [5, 3, 6]]

Merge Rules: Already learned using BPE

Next Token Prediction Completed Successfully!

Project Completed Successfully!
